import './globals.css'
import { Darker_Grotesque  } from 'next/font/google'

const darker = Darker_Grotesque({ subsets: ['latin'] })

export const metadata = {
  title: 'Maximus',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={darker.className}>{children}</body>
    </html>
  )
}
